version: "2.4"
services:
  #Eureka server
  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka-server
    image: eureka-server:0.0.1
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761" ]
      interval: 10s
      retries: 5
      start_period: 1200s
    networks:
      - rlb-net

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok" ]
      interval: 10s
      retries: 5
      start_period: 1200s
    restart: on-failure
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
    - rlb-net

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_4LW_COMMANDS_WHITELIST: "ruok,stat"
    restart: on-failure
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "bash", "-c", "echo ruok | nc localhost 2181"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 1200s
    networks:
      - rlb-net


  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: on-failure
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1200s
    networks:
      - rlb-net

  #RLB-Notification
  rlb-notification:
    container_name: rlb-notification
    build:
      context: ./rlb-notification
    image: rlb-notification:0.0.1
    ports:
      - "6060:6060"
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: rlb-notification
      SPRING_PROFILES_ACTIVE: prod
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka

    restart: on-failure
    networks:
      - rlb-net

  rlb-oc:
    container_name: rlb-oc
    build:
      context: ./rlb-oc
    image: rlb-oc:0.0.1
    ports:
      - "6061:6061"
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: rlb-oc
      SPRING_PROFILES_ACTIVE: prod
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    restart: on-failure
    networks:
      - rlb-net

networks:
  rlb-net:
    driver: bridge
