version: "3"
services:
  eureka-server:
    container_name: eureka-server
    image: eureka-server:0.0.1
    ports:
      - "8761:8761"
    networks:
      - rlb-net
#docker run -d eureka-server:0.0.1 -p8761:8761 --name=eureka-server
#RLB-Notification
  rlb-notification:
    container_name: rlb-notification
    image: rlb-notification:0.0.1
    ports:
      - "6060:6060"
    depends_on:
      - eureka-server
    networks:
      - rlb-net

  rlb-oc:
    container_name: rlb-oc
    image: rlb-oc:0.0.1
    ports:
      - "6061:6061"
    depends_on:
      - eureka-server
      - mysql
    networks:
      - rlb-net

  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: relo_budy
    ports:
      - "3306:3306"
    networks:
      - rlb-net

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - rlb-net

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - rlb-net

networks:
  rlb-net:
    driver: bridge