version: "2.4"
services:
  #Mongo
  mongodb:
    container_name: mongodb
    image: mongo:6.0
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: on-failure
    networks:
      - rlb-net

    #Zookeeper
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.6.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_4LW_COMMANDS_WHITELIST: "ruok,stat"
    restart: on-failure
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo ruok | nc localhost 2181" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - rlb-net
  #Kafka Server
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: on-failure
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - rlb-net

  #Eureka server
  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka-server
    image: eureka-server:0.0.1
    ports:
      - "8761:8761"
    environment:
      SPRING_APPLICATION_NAME: eureka-server
      SPRING_PROFILES_ACTIVE: prod
    restart: on-failure
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761 || exit 1"]
      interval: 10s
      retries: 5
      start_period: 120s
    networks:
      - rlb-net
  #RLB-Notification
  rlb-notification:
    container_name: rlb-notification
    build:
      context: ./rlb-notification
    image: rlb-notification:0.0.1
    ports:
      - "6060:6060"
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: rlb-notification
      SPRING_PROFILES_ACTIVE: prod
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    restart: on-failure
    networks:
      - rlb-net

  rlb-oc:
    container_name: rlb-oc
    build:
      context: ./rlb-oc
    image: rlb-oc:0.0.1
    ports:
      - "6061:6061"
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: rlb-oc
      SPRING_PROFILES_ACTIVE: prod
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    restart: on-failure
    networks:
      - rlb-net

networks:
  rlb-net:
    driver: bridge
