version: "3.4"
services:
  #Eureka server
  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka-server
    image: eureka-server:0.0.1
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761" ]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - rlb-net

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - rlb-net

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    healthcheck:
      test: [ "CMD", "sh", "-c", "echo ruok | nc 127.0.0.1 2181 | grep imok" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rlb-net



  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - rlb-net

  #RLB-Notification
  rlb-notification:
    container_name: rlb-notification
    build:
      context: ./rlb-notification
    image: rlb-notification:0.0.1
    ports:
      - "6060:6060"
    depends_on:
      - eureka-server
    environment:
      SPRING_APPLICATION_NAME: rlb-notification
      SPRING_PROFILES_ACTIVE: prod

    restart: on-failure
    networks:
      - rlb-net
  rlb-oc:
    container_name: rlb-oc
    build:
      context: ./rlb-oc
    image: rlb-oc:0.0.1
    ports:
      - "6061:6061"
    depends_on:
      - eureka-server
      - mongodb
      - zookeeper
      - kafka
    environment:
      SPRING_APPLICATION_NAME: rlb-oc
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - rlb-net
networks:
  rlb-net:
    driver: bridge