server:
  port: 6061
spring:
  application:
    name: rlb-oc

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}
  #Kafka Consumer
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: rlbGroup
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.rlb.payload.UserCreatedEvent
    #Kafka Producer
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#MongoDB
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: rlb
