spring:
  application:
    name: rlb-oh
  #Kafka Consumer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: rlbGroup
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-attempts: 3
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.rlb.oc.event.OrderCreateEvent
        spring.json.trusted.packages: "*"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topics:
      orderCreated: order.created.v1
      dlq: order.created.v1.DLQ


  data:
    mongodb:
      uri: mongodb://localhost:27017/orderservice
      auto-index-creation: true  

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}