spring:
  application:
    name: eureka-config

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: rlbGroup
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.rlb.payload.UserCreatedEvent
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
