spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8761

#root logging
logging:
  level:
    #root: INFO

   # org:
   #springframework:
   #   web: ERROR

    com:
      rlb: ERROR
  file:
    name: D:\eureka.log