server:
  port: 8761
  address: 0.0.0.0    #This ensures the Eureka app is accessible inside the container via localhost and from other containers via eureka-server:8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


