server:
  port: 9093

spring:
  application:
    name: rpb-gateway

  datasource:
    url: jdbc:mysql://localhost:3306/relo_budy?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: never