server:
  port: 9093
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/relo_budy?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    initialization-mode: always

  sql:
    init:
      mode: always    # Ensures data.sql runs
      continue-on-error: true