server:
  port: 9093
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/relo_budy?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    initialization-mode: always

  sql:
    init:
      mode: always    # Ensures data.sql runs
      continue-on-error: true
  dialect:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update

  application:
    name: rlb-core

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}