server:
  port: 9093
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/relo_budy?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root


  dialect:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update