server:
  port: 8081

spring:
  application:
    name: rlb-api-gateway

  cloud:
    gateway:
      routes:
        - id: rlb-common
          uri: lb://rlb-common
          predicates:
            - Path=/api/v1/common/**
          filters:
            - AuthenticationFilter

        - id: rlb-core
          uri: lb://rlb-core
          predicates:
            - Path=/api/v1/core/**, /team/**
          filters:
            - AuthenticationFilter

        - id: rlb-auth
          uri: lb://rlb-auth
          predicates:
            - Path=/auth/**

        - id: rlb-oc
          uri: lb://rlb-oc
          predicates:
            - Path=/api/v1/order-capture/**
          filters:
            - AuthenticationFilter

        - id: rlb-oh
          uri: lb://rlb-oh
          predicates:
            - Path=/api/v1/order-handle/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}