server:
  port: 8081

spring:
  application:
    name: rlb-api-gateway

  cloud:
    gateway:
      routes:
        - id: rlb-common
          uri: lb://rlb-common
          predicates:
            - Path=/common/**
          filters:
            - AuthenticationFilter

        - id: rlb-core
          uri: lb://rlb-core
          predicates:
            - Path=/core/**, /team/**
          filters:
            - AuthenticationFilter

        - id: rlb-auth
          uri: lb://rlb-auth
          predicates:
            - Path=/auth/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}