package com.rlb.oh.dlq.entity;

import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import java.time.Instant;

// dlq/entity/DlqEvent.java
@Document(collection = "dlq_events")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class DlqEvent {

    @Id
    private String id;                    // auto generated by MongoDB (ObjectId)

    @Field("payload")
    private String payload;               // original failed message as string

    @Field("original_topic")
    private String originalTopic;         // e.g. order.created.v1

    @Field("original_partition")
    private Integer originalPartition;    // partition it came from

    @Field("original_offset")
    private Long originalOffset;          // offset it came from

    @Field("original_timestamp")
    private Instant originalTimestamp;    // when it was originally published

    @Field("exception_class")
    private String exceptionClass;        // e.g. java.lang.RuntimeException

    @Field("exception_message")
    private String exceptionMessage;      // e.g. "DB connection failed"

    @Field("stack_trace")
    private String stackTrace;            // full stack trace

    @Field("dlq_received_at")
    private Instant dlqReceivedAt;        // when it arrived in DLQ

    @Field("status")
    private DlqEventStatus status;        // PENDING / REPLAYED / DISCARDED

    @Field("replayed_at")
    private Instant replayedAt;           // set when operator replays

    @Field("discarded_at")
    private Instant discardedAt;          // set when operator discards

    @Field("remarks")
    private String remarks;               // operator notes

    // ─────────────────────────────────────────────────────────
    // State transition methods — kept manual intentionally
    // These are business actions, not just setters
    // ─────────────────────────────────────────────────────────
    public void markReplayed(String remarks) {
        this.status     = DlqEventStatus.REPLAYED;
        this.replayedAt = Instant.now();
        this.remarks    = remarks;
    }

    public void markDiscarded(String remarks) {
        this.status      = DlqEventStatus.DISCARDED;
        this.discardedAt = Instant.now();
        this.remarks     = remarks;
    }
}