#twilio:
#  accountSid: AC9dae9374e459593c7de4868c04b77284
#  authToken: edd4949c4724dcb4b104996d61e317bc
#  phoneNumber: +18563863439

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: icible0@gmail.com
    password: hfti tmfj rsgw spst
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

