#spring:
#  profiles:
#    active: uat

twilio:
  accountSid: AC3051284f3dbb6c59c42e9563715e2f35
  authToken: cf981b6576c2b7ee4447a5aba74dacf5
  #WhatsAPP Msg
  phoneNumber: +14155238886
  #Text Msg
  #phoneNumber: +18563863439

order:
  placed: "Thank you for your order. Your delivery is scheduled for {0} at {1}. If you need to change it, please reply back and let us know."

ORDER_CREATED_MSG: "Your Order successfully placed on DEV"